networks:
  megio-apps:

volumes:
  postgres_data:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: "no"
    environment:
      QUEUE_WORKERS_ENABLED: ${QUEUE_WORKERS_ENABLED}
    networks:
      - megio-apps
    ports:
      - "8090:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/http.d/default.conf:/etc/nginx/http.d/default.conf
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - $PWD:/var/www/html:cached

  postgres:
    image: postgres:16
    #restart: on-failure because postgres shutdown on first creation (permissions problem)
    restart: "on-failure"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    networks:
      - megio-apps
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - $PWD/docker/temp:/var/lib/postgresql/temp